version: '3'

services:
  terminal:
    #image: ghcr.io/m4tt72/terminal:svelte
    build: .
    container_name: terminal
    restart: unless-stopped
    ports:
      - '0.0.0.0:${PORT:-3000}:${PORT:-3000}'
    command: >
      -f
      -v
      -p ${PORT:-3000}
      -c httpd.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}"]
      interval: 200s
      timeout: 200s
      retries: 5
